FROM node:22-slim AS deps
WORKDIR /opt/env/work

COPY frontend/package.json frontend/package-lock.json ./

RUN npm -v && npm i -g npm@11 && npm -v

RUN npm install --package-lock-only --include=optional

RUN npm ci --include=optional

RUN mkdir -p /opt/env/dev /opt/env/prod \
 && cp -a node_modules /opt/env/dev/node_modules

RUN rm -rf node_modules \
 && npm ci --omit=dev --include=optional \
 && cp -a node_modules /opt/env/prod/node_modules

RUN node -p "process.platform + ' ' + process.arch" \
 && ls -1 /opt/env/dev/node_modules/@rollup | grep linux-x64

RUN useradd -m appuser

FROM node:22-slim AS env
WORKDIR /opt/env

COPY --from=deps /opt/env/dev  ./dev
COPY --from=deps /opt/env/prod ./prod
RUN useradd -m appuser
