FROM node:22-slim AS deps
WORKDIR /opt/env/work

COPY frontend/package.json frontend/package-lock.json ./

RUN npm ci

RUN mkdir -p /opt/env/dev /opt/env/prod \
 && cp -a /opt/env/work/node_modules /opt/env/dev/node_modules \
 && cp -a /opt/env/work/node_modules /opt/env/prod/node_modules \
 && npm prune --omit=dev \
 && cp -a /opt/env/work/node_modules /opt/env/prod/node_modules

RUN useradd -m appuser

FROM node:22-slim AS env
WORKDIR /opt/env

COPY --from=deps /opt/env/dev  ./dev
COPY --from=deps /opt/env/prod ./prod
RUN useradd -m appuser
