export const TestData = [
  {
    id: 1,
    avatar: "https://i.pravatar.cc/150?img=32",
    fullName: "Ha Vu",
    email: "havuct@example.com",
    department: "Kim Bao Son",
    accountStatus: "Active",
    role: "Admin",
  },
  {
    id: 2,
    avatar: "https://i.pravatar.cc/150?img=15",
    fullName: "David Nguyen",
    email: "david.nguyen@example.com",
    department: "Hoa An department",
    accountStatus: "Inactive",
    role: "User",
  },
  {
    id: 3,
    avatar: "https://i.pravatar.cc/150?img=48",
    fullName: "Alice Truong",
    email: "alice.truong@example.com",
    department: "Giang Dien Plant",
    accountStatus: "Active",
    role: "Supervisor",
  },
  {
    id: 4,
    avatar: "https://i.pravatar.cc/150?img=10",
    fullName: "Ha Vu",
    email: "havuct@example.com",
    department: "Kim Bao Son",
    accountStatus: "Active",
    role: "Admin",
  },
  {
    id: 5,
    avatar: "https://i.pravatar.cc/150?img=11",
    fullName: "David Nguyen",
    email: "david.nguyen@example.com",
    department: "Hoa An department",
    accountStatus: "Inactive",
    role: "User",
  },
  {
    id: 6,
    avatar: "https://i.pravatar.cc/150?img=12",
    fullName: "Alice Truong",
    email: "alice.truong@example.com",
    department: "Giang Dien Plant",
    accountStatus: "Active",
    role: "Supervisor",
  },
  {
    id: 7,
    avatar: "https://i.pravatar.cc/150?img=13",
    fullName: "Ha Vu",
    email: "havuct@example.com",
    department: "Kim Bao Son",
    accountStatus: "Active",
    role: "Admin",
  },
  {
    id: 8,
    avatar: "https://i.pravatar.cc/150?img=14",
    fullName: "David Nguyen",
    email: "david.nguyen@example.com",
    department: "Hoa An department",
    accountStatus: "Inactive",
    role: "User",
  },
  {
    id: 9,
    avatar: "https://i.pravatar.cc/150?img=16",
    fullName: "Alice Truong",
    email: "alice.truong@example.com",
    department: "Giang Dien Plant",
    accountStatus: "Active",
    role: "Supervisor",
  },
  {
    id: 10,
    avatar: "https://i.pravatar.cc/150?img=17",
    fullName: "Ha Vu",
    email: "havuct@example.com",
    department: "Kim Bao Son",
    accountStatus: "Active",
    role: "Admin",
  },
  {
    id: 11,
    avatar: "https://i.pravatar.cc/150?img=18",
    fullName: "David Nguyen",
    email: "david.nguyen@example.com",
    department: "Hoa An department",
    accountStatus: "Inactive",
    role: "User",
  },
  {
    id: 12,
    avatar: "https://i.pravatar.cc/150?img=19",
    fullName: "Alice Truong",
    email: "alice.truong@example.com",
    department: "Giang Dien Plant",
    accountStatus: "Active",
    role: "Supervisor",
  },
];